name: men_barde
description: Mobile geolocation app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_analytics: ^9.1.7
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
  firebase_performance: ^0.8.0+11
  
  go_router: ^3.1.0
  
  google_maps_flutter: ^2.1.5
  google_fonts: ^2.3.2
  intl: ^0.17.0

  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4
  
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  logger: ^1.1.0
  retrofit: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  
  freezed: ^2.0.3+1
  retrofit_generator: ^4.0.1

flutter:

  uses-material-design: true
